# -*- coding: utf-8 -*-
"""Assignment 3 - Functions and Module .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQsxx1DG7U4AzkgxvfN0F55WLJCF5zO7

Task 1: Calculate Factorial Using a Function
"""

## factorial
#0! = 1
#1! = 1 * 0! = 1*1 = 1
#2! = 2 * 1! = 2 * 1 = 2
#3! = 3 * 2! = 3 * 2 = 6
#4! = 4 * 3! = 4 * 3! = 4 * 6 = 24
#5! = 5 * 4! = 5 * 24 = 120

## factorial
factorial_number = int(input("Enter a number:"))

def factorial(factorial_number):
  if factorial_number < 1:
    return 1
  else:
    return factorial_number * factorial(factorial_number-1)

number = factorial(factorial_number)
print("Factorial of" ,factorial_number,"is: ", number)


# number = factorial(4)
# print(number)

# number_2 = factorial(5)
# print(number_2)

"""Task 2: Using the Math Module for Calculations"""

## import all the package of math module
from math import *

math_number = int(input(" Please provide a number: "))
square_root = sqrt(math_number)
natural_log = log(math_number)
radian_number = sin(math_number)

print("Square Root: " ,square_root)
print("Logarithm: " ,natural_log)
print("Sine " ,radian_number)