# -*- coding: utf-8 -*-
"""ASSIGNMENT 4: Files, Exceptions, and Errors in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gu6Dld9dzvhqmwMoOKB8TDCHWptM_hYg

Problem Statement:  Write a Python program that:
1.   Opens and reads a text file named sample.txt.
2.   Prints its content line by line.
3.   Handles errors gracefully if the file does not exist.
"""

## error handles
try:
  file = open('sample.txt','r')
  print("Reading File Content")
except FileNotFoundError:
    print(" Error : The file 'sample.txt' was not found")

with open('sample.txt','w') as file:
  writing_file_file = file.write("Line 1 : This is sample text file.\n")
  print(writing_file)

with open('sample.txt','a') as file:
  appending_file = file.write("Line 2: It Contains multiple lines")
  print(appending_file)

file1 = open('sample.txt','r')
print(file1.read())

try:
  file = open('sample.txt','r')
  print("Reading File Content :")
except FileNotFoundError:
    print(" Error : The file 'sample.txt' was not found")


with open('sample.txt','w') as file:
  writing_file_file = file.write("Line 1 : This is sample text file.\n")
  #print(writing_file)


with open('sample.txt','a') as file:
  appending_file = file.write("Line 2: It Contains multiple lines")
  #print(appending_file)


file1 = open('sample.txt','r')
print(file1.read())

"""Problem Statement: Write a Python program that:
1.   Takes user input and writes it to a file named output.txt.
2.   Appends additional data to the same file.
3.   Reads and displays the final content of the file.
"""

file = input("Enter text to write to the file: ")
file1 = open("output.txt",'w')
file1.write(file)
print("Data Successfully written to output.txt")
file1.close()

file2 = input("Enter additional text to append: ")
file1 = open("output.txt",'a')
file1.write(file2)
print("Data Successfully appended")
file1.close()

file1 = open('output.txt','r')
reading_file = file1.read()
print("Final content of output.txt: \n",reading_file)
file1.close()