# -*- coding: utf-8 -*-
"""Tutedude 2nd Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/191BjCdhoJEBdyTuFKcw5JPkWKC0tsiuk
"""

## Take integer input tells whether the value is even or odd

value = int(input("Enter a number : "))
if value % 2 == 0:
  print(value, "is an even number")
else:
  print(value, "is an odd number")

total_sum = 0
for i in range(1,51):
  total_sum += i
print("The total sum of range 1 to 50 is :", total_sum)